services:
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data-1/db
    ports:
      - 27017:27017
    expose:
      - 27017
  twirler:
    env_file:
      - .env_compose
    restart: always
    container_name: twirler
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8081:8081"
    expose:
      - 8081
  zookeeper:
    container_name: zookeeper
    restart: always
    image: wurstmeister/zookeeper
  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    expose:
      - 9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "gt.stat:1:1"
    volumes:
      - kafka-data:/data/kafka
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8082:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true

volumes:
  mongodb-data:
  kafka-data: