// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v1/slot.proto

package twirlerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlotCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *SlotCreateRequest) Reset() {
	*x = SlotCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCreateRequest) ProtoMessage() {}

func (x *SlotCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCreateRequest.ProtoReflect.Descriptor instead.
func (*SlotCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{0}
}

func (x *SlotCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SlotCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *SlotCreateResponse) Reset() {
	*x = SlotCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlotCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotCreateResponse) ProtoMessage() {}

func (x *SlotCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotCreateResponse.ProtoReflect.Descriptor instead.
func (*SlotCreateResponse) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{1}
}

func (x *SlotCreateResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type AttachBannerToSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID uint64 `protobuf:"varint,1,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
	SlotID   uint64 `protobuf:"varint,2,opt,name=slotID,proto3" json:"slotID,omitempty"`
}

func (x *AttachBannerToSlotRequest) Reset() {
	*x = AttachBannerToSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerToSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerToSlotRequest) ProtoMessage() {}

func (x *AttachBannerToSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerToSlotRequest.ProtoReflect.Descriptor instead.
func (*AttachBannerToSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{2}
}

func (x *AttachBannerToSlotRequest) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *AttachBannerToSlotRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

type AttachBannerToSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttachBannerToSlotResponse) Reset() {
	*x = AttachBannerToSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerToSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerToSlotResponse) ProtoMessage() {}

func (x *AttachBannerToSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerToSlotResponse.ProtoReflect.Descriptor instead.
func (*AttachBannerToSlotResponse) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{3}
}

type DetachBannerToSlotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   uint64 `protobuf:"varint,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID uint64 `protobuf:"varint,2,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *DetachBannerToSlotRequest) Reset() {
	*x = DetachBannerToSlotRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerToSlotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerToSlotRequest) ProtoMessage() {}

func (x *DetachBannerToSlotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerToSlotRequest.ProtoReflect.Descriptor instead.
func (*DetachBannerToSlotRequest) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{4}
}

func (x *DetachBannerToSlotRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *DetachBannerToSlotRequest) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

type DetachBannerToSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DetachBannerToSlotResponse) Reset() {
	*x = DetachBannerToSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_slot_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerToSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerToSlotResponse) ProtoMessage() {}

func (x *DetachBannerToSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_slot_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerToSlotResponse.ProtoReflect.Descriptor instead.
func (*DetachBannerToSlotResponse) Descriptor() ([]byte, []int) {
	return file_v1_slot_proto_rawDescGZIP(), []int{5}
}

var File_v1_slot_proto protoreflect.FileDescriptor

var file_v1_slot_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x73, 0x6c, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x11, 0x53,
	0x6c, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x6c, 0x6f, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x4f, 0x0a, 0x19, 0x41, 0x74, 0x74, 0x61,
	0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x22, 0x1c, 0x0a, 0x1a, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4f, 0x0a, 0x19, 0x44, 0x65, 0x74, 0x61, 0x63,
	0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x74, 0x61,
	0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x54, 0x6f, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x14, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65,
	0x72, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x76, 0x31, 0xca, 0x02,
	0x0a, 0x54, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_slot_proto_rawDescOnce sync.Once
	file_v1_slot_proto_rawDescData = file_v1_slot_proto_rawDesc
)

func file_v1_slot_proto_rawDescGZIP() []byte {
	file_v1_slot_proto_rawDescOnce.Do(func() {
		file_v1_slot_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_slot_proto_rawDescData)
	})
	return file_v1_slot_proto_rawDescData
}

var file_v1_slot_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_slot_proto_goTypes = []interface{}{
	(*SlotCreateRequest)(nil),          // 0: twirler.v1.SlotCreateRequest
	(*SlotCreateResponse)(nil),         // 1: twirler.v1.SlotCreateResponse
	(*AttachBannerToSlotRequest)(nil),  // 2: twirler.v1.AttachBannerToSlotRequest
	(*AttachBannerToSlotResponse)(nil), // 3: twirler.v1.AttachBannerToSlotResponse
	(*DetachBannerToSlotRequest)(nil),  // 4: twirler.v1.DetachBannerToSlotRequest
	(*DetachBannerToSlotResponse)(nil), // 5: twirler.v1.DetachBannerToSlotResponse
}
var file_v1_slot_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_slot_proto_init() }
func file_v1_slot_proto_init() {
	if File_v1_slot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_slot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_slot_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlotCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_slot_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachBannerToSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_slot_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachBannerToSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_slot_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachBannerToSlotRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_slot_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachBannerToSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_slot_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_slot_proto_goTypes,
		DependencyIndexes: file_v1_slot_proto_depIdxs,
		MessageInfos:      file_v1_slot_proto_msgTypes,
	}.Build()
	File_v1_slot_proto = out.File
	file_v1_slot_proto_rawDesc = nil
	file_v1_slot_proto_goTypes = nil
	file_v1_slot_proto_depIdxs = nil
}
