// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: v1/twirler_api.proto

package twirlerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID uint64 `protobuf:"varint,1,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
	SlotID   uint64 `protobuf:"varint,2,opt,name=slotID,proto3" json:"slotID,omitempty"`
}

func (x *AttachBannerRequest) Reset() {
	*x = AttachBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerRequest) ProtoMessage() {}

func (x *AttachBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerRequest.ProtoReflect.Descriptor instead.
func (*AttachBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{0}
}

func (x *AttachBannerRequest) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *AttachBannerRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

type AttachBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AttachBannerResponse) Reset() {
	*x = AttachBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttachBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachBannerResponse) ProtoMessage() {}

func (x *AttachBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachBannerResponse.ProtoReflect.Descriptor instead.
func (*AttachBannerResponse) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{1}
}

type DetachBannerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID   uint64 `protobuf:"varint,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID uint64 `protobuf:"varint,2,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *DetachBannerRequest) Reset() {
	*x = DetachBannerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerRequest) ProtoMessage() {}

func (x *DetachBannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerRequest.ProtoReflect.Descriptor instead.
func (*DetachBannerRequest) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{2}
}

func (x *DetachBannerRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *DetachBannerRequest) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

type DetachBannerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DetachBannerResponse) Reset() {
	*x = DetachBannerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetachBannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachBannerResponse) ProtoMessage() {}

func (x *DetachBannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachBannerResponse.ProtoReflect.Descriptor instead.
func (*DetachBannerResponse) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{3}
}

type IncrementCountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID        uint64 `protobuf:"varint,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	BannerID      uint64 `protobuf:"varint,2,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
	SocialGroupID uint64 `protobuf:"varint,3,opt,name=socialGroupID,proto3" json:"socialGroupID,omitempty"`
}

func (x *IncrementCountRequest) Reset() {
	*x = IncrementCountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementCountRequest) ProtoMessage() {}

func (x *IncrementCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementCountRequest.ProtoReflect.Descriptor instead.
func (*IncrementCountRequest) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{4}
}

func (x *IncrementCountRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *IncrementCountRequest) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

func (x *IncrementCountRequest) GetSocialGroupID() uint64 {
	if x != nil {
		return x.SocialGroupID
	}
	return 0
}

type IncrementCountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *IncrementCountResponse) Reset() {
	*x = IncrementCountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IncrementCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementCountResponse) ProtoMessage() {}

func (x *IncrementCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementCountResponse.ProtoReflect.Descriptor instead.
func (*IncrementCountResponse) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{5}
}

type GimmeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SlotID        uint64 `protobuf:"varint,1,opt,name=slotID,proto3" json:"slotID,omitempty"`
	SocialGroupId uint64 `protobuf:"varint,2,opt,name=socialGroupId,proto3" json:"socialGroupId,omitempty"`
}

func (x *GimmeRequest) Reset() {
	*x = GimmeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GimmeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GimmeRequest) ProtoMessage() {}

func (x *GimmeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GimmeRequest.ProtoReflect.Descriptor instead.
func (*GimmeRequest) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{6}
}

func (x *GimmeRequest) GetSlotID() uint64 {
	if x != nil {
		return x.SlotID
	}
	return 0
}

func (x *GimmeRequest) GetSocialGroupId() uint64 {
	if x != nil {
		return x.SocialGroupId
	}
	return 0
}

type GimmeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BannerID uint64 `protobuf:"varint,1,opt,name=bannerID,proto3" json:"bannerID,omitempty"`
}

func (x *GimmeResponse) Reset() {
	*x = GimmeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_twirler_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GimmeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GimmeResponse) ProtoMessage() {}

func (x *GimmeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_twirler_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GimmeResponse.ProtoReflect.Descriptor instead.
func (*GimmeResponse) Descriptor() ([]byte, []int) {
	return file_v1_twirler_api_proto_rawDescGZIP(), []int{7}
}

func (x *GimmeResponse) GetBannerID() uint64 {
	if x != nil {
		return x.BannerID
	}
	return 0
}

var File_v1_twirler_api_proto protoreflect.FileDescriptor

var file_v1_twirler_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x76, 0x31, 0x2f, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x49, 0x0a, 0x13, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x22, 0x16, 0x0a,
	0x14, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x13, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42,
	0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x6c,
	0x6f, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44,
	0x22, 0x16, 0x0a, 0x14, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x71, 0x0a, 0x15, 0x49, 0x6e, 0x63, 0x72,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x0a, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x49,
	0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x47, 0x69, 0x6d, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x49, 0x44, 0x12, 0x24, 0x0a,
	0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x49, 0x64, 0x22, 0x2b, 0x0a, 0x0d, 0x47, 0x69, 0x6d, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x49, 0x44,
	0x32, 0xc9, 0x02, 0x0a, 0x0a, 0x54, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x41, 0x50, 0x49, 0x12,
	0x51, 0x0a, 0x0c, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x12,
	0x1f, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74, 0x74,
	0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x51, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x72, 0x12, 0x1f, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x65, 0x74, 0x61, 0x63, 0x68, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x0e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x74, 0x77, 0x69,
	0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c,
	0x0a, 0x05, 0x47, 0x69, 0x6d, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x69, 0x6d, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x69, 0x6d, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23, 0x5a, 0x14,
	0x74, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x77, 0x69, 0x72, 0x6c,
	0x65, 0x72, 0x76, 0x31, 0xca, 0x02, 0x0a, 0x54, 0x77, 0x69, 0x72, 0x6c, 0x65, 0x72, 0x5c, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_twirler_api_proto_rawDescOnce sync.Once
	file_v1_twirler_api_proto_rawDescData = file_v1_twirler_api_proto_rawDesc
)

func file_v1_twirler_api_proto_rawDescGZIP() []byte {
	file_v1_twirler_api_proto_rawDescOnce.Do(func() {
		file_v1_twirler_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_twirler_api_proto_rawDescData)
	})
	return file_v1_twirler_api_proto_rawDescData
}

var file_v1_twirler_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_twirler_api_proto_goTypes = []interface{}{
	(*AttachBannerRequest)(nil),    // 0: twirler.v1.AttachBannerRequest
	(*AttachBannerResponse)(nil),   // 1: twirler.v1.AttachBannerResponse
	(*DetachBannerRequest)(nil),    // 2: twirler.v1.DetachBannerRequest
	(*DetachBannerResponse)(nil),   // 3: twirler.v1.DetachBannerResponse
	(*IncrementCountRequest)(nil),  // 4: twirler.v1.IncrementCountRequest
	(*IncrementCountResponse)(nil), // 5: twirler.v1.IncrementCountResponse
	(*GimmeRequest)(nil),           // 6: twirler.v1.GimmeRequest
	(*GimmeResponse)(nil),          // 7: twirler.v1.GimmeResponse
}
var file_v1_twirler_api_proto_depIdxs = []int32{
	0, // 0: twirler.v1.TwirlerAPI.AttachBanner:input_type -> twirler.v1.AttachBannerRequest
	2, // 1: twirler.v1.TwirlerAPI.DetachBanner:input_type -> twirler.v1.DetachBannerRequest
	4, // 2: twirler.v1.TwirlerAPI.IncrementCount:input_type -> twirler.v1.IncrementCountRequest
	6, // 3: twirler.v1.TwirlerAPI.Gimme:input_type -> twirler.v1.GimmeRequest
	1, // 4: twirler.v1.TwirlerAPI.AttachBanner:output_type -> twirler.v1.AttachBannerResponse
	3, // 5: twirler.v1.TwirlerAPI.DetachBanner:output_type -> twirler.v1.DetachBannerResponse
	5, // 6: twirler.v1.TwirlerAPI.IncrementCount:output_type -> twirler.v1.IncrementCountResponse
	7, // 7: twirler.v1.TwirlerAPI.Gimme:output_type -> twirler.v1.GimmeResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_twirler_api_proto_init() }
func file_v1_twirler_api_proto_init() {
	if File_v1_twirler_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_twirler_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttachBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachBannerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetachBannerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementCountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IncrementCountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GimmeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_twirler_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GimmeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_twirler_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_twirler_api_proto_goTypes,
		DependencyIndexes: file_v1_twirler_api_proto_depIdxs,
		MessageInfos:      file_v1_twirler_api_proto_msgTypes,
	}.Build()
	File_v1_twirler_api_proto = out.File
	file_v1_twirler_api_proto_rawDesc = nil
	file_v1_twirler_api_proto_goTypes = nil
	file_v1_twirler_api_proto_depIdxs = nil
}
